export type ToolCategory = 'PDF' | 'Image' | 'Text' | 'Developer' | 'Network' | 'Utility';

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  popular?: boolean;
  related?: string[];
};

export const tools: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and compact JSON data instantly.',
    category: 'Developer',
    icon: '/icons/json.svg',
    popular: true,
    related: ['url-encoder', 'markdown-preview'],
  },
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size while keeping layout intact.',
    category: 'PDF',
    icon: '/icons/pdf.svg',
    popular: true,
    related: ['pdf-split', 'pdf-merge'],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images for web, social media, and presentations.',
    category: 'Image',
    icon: '/icons/image.svg',
    popular: true,
    related: ['image-compressor', 'image-converter'],
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size while maintaining good quality.',
    category: 'Image',
    icon: '/icons/image.svg',
    popular: true,
    related: ['image-resizer', 'image-converter'],
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images to any size directly in your browser.',
    category: 'Image',
    icon: '/icons/image.svg',
    related: ['image-resizer', 'image-converter'],
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Switch text between uppercase, lowercase, title case, and more.',
    category: 'Text',
    icon: '/icons/text.svg',
    related: ['word-counter', 'character-counter'],
  },
  {
    slug: 'ping-test',
    name: 'Ping Server',
    description: 'Test server latency and browser connectivity with a simple request.',
    category: 'Network',
    icon: '/icons/ping.svg',
    related: ['ip-lookup'],
  },
  {
    slug: 'calculator',
    name: 'Calculator',
    description: 'Perform quick calculations with a clean, responsive interface.',
    category: 'Utility',
    icon: '/icons/calculator.svg',
    related: ['unit-converter'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate version 4 UUIDs instantly for identifiers and unique keys.',
    category: 'Developer',
    icon: '/icons/uuid.svg',
    related: ['password-generator'],
  },
  {
    slug: 'base64-encoder',
    name: 'Base64 Encoder',
    description: 'Encode and decode text quickly using Base64 encoding.',
    category: 'Developer',
    icon: '/icons/base64.svg',
    related: ['sha-256-generator', 'text-case-converter'],
  },
  {
    slug: 'sha-256-generator',
    name: 'SHA-256 Generator',
    description: 'Create SHA-256 hashes for messages, passwords, and verification.',
    category: 'Developer',
    icon: '/icons/sha.svg',
    related: ['base64-encoder', 'password-generator'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Create secure passwords with customizable length and character options.',
    category: 'Developer',
    icon: '/icons/password.svg',
    related: ['json-formatter'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT tokens instantly without uploading data.',
    category: 'Developer',
    icon: '/icons/jwt.svg',
    related: ['json-formatter', 'base64-encoder'],
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder',
    description: 'Encode and decode URLs safely.',
    category: 'Developer',
    icon: '/icons/text.svg',
    related: ['json-formatter', 'base64-encoder'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions in real time.',
    category: 'Developer',
    icon: '/icons/text.svg',
    related: ['text-case-converter'],
  },
  {
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between formats like PNG, JPEG, and WebP directly in the browser.',
    category: 'Image',
    icon: '/icons/image.svg',
    related: ['image-resizer', 'image-to-pdf'],
  },
  {
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert uploaded images into a PDF page with automatic scaling.',
    category: 'PDF',
    icon: '/icons/pdf.svg',
    related: ['image-converter', 'image-resizer'],
  },
  {
    slug: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Extract selected pages or split PDFs into multiple files.',
    category: 'PDF',
    icon: '/icons/pdf.svg',
    popular: true,
    related: ['pdf-merge', 'pdf-compressor'],
  },
  {
    slug: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages into high-quality PNG or JPG images.',
    category: 'PDF',
    icon: '/icons/pdf.svg',
    related: ['image-converter', 'image-resizer'],
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate customizable QR Codes instantly.',
    category: 'Utility',
    icon: '/icons/qr.svg',
    popular: true,
    related: ['password-generator', 'base64-encoder'],
  },
  {
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Create Code128, EAN, and QR barcodes online.',
    category: 'Utility',
    icon: '/icons/barcode.svg',
    related: ['qr-code-generator', 'image-converter'],
  },
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers with custom ranges.',
    category: 'Utility',
    icon: '/icons/calculator.svg',
    related: ['calculator', 'uuid-generator'],
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF files into one secure document.',
    category: 'PDF',
    icon: '/icons/pdf.svg',
    related: ['pdf-split', 'pdf-compressor'],
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Render Markdown instantly and copy the formatted output.',
    category: 'Developer',
    icon: '/icons/markdown.svg',
    related: ['json-formatter'],
  },
];

export const categories = [
  { key: 'PDF', label: 'PDF' },
  { key: 'Image', label: 'Image' },
  { key: 'Text', label: 'Text' },
  { key: 'Developer', label: 'Developer' },
  { key: 'Network', label: 'Network' },
  { key: 'Utility', label: 'Utility' },
] as const;
